# Generated by Django 5.2.8 on 2025-12-02 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='singleton_enforcer',
            field=models.BooleanField(default=True, editable=False, unique=True),
        ),
    ]
